# Generated by Django 3.1.4 on 2022-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_count',
            field=models.IntegerField(null=True),
        ),
    ]
