# Generated by Django 3.1.4 on 2022-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20220428_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='d_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
