# Generated by Django 3.1.4 on 2022-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20220428_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
